packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  prisma: true

nodeLinker: hoisted
packageImportMethod: copy
preferSymlinkedExecutables: false
verifyDepsBeforeRun: false
